[package]
name = "pingRs"
version = "1.1"
edition = "2024"


[profile.release]
strip = true
opt-level = "s"
codegen-units = 1
lto = true

[dependencies]
clap = { version = "4.5.48", features = ["derive"] }


[build-dependencies]
